package resolvers

import (
	"context"
	"errors"
	"strings"

	"github.com/bitmagnet-io/bitmagnet/internal/config/configapply"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/auth"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel/gen"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// This file is NOT generated by gqlgen. Helper functions used by resolvers
// live here so they survive `task gen-gql` regeneration. gqlgen relocates any
// non-resolver helper it finds inside *.resolvers.go into a commented-out
// "!!! WARNING !!!" block, which breaks the build because the call site is
// left intact. Keeping helpers in a separate non-generated file avoids that.

// configRuntimeChangeability reports whether a section has a registered
// live-apply path.
func configRuntimeChangeability(
	changeability configapply.Changeability,
	sectionKey string,
) gen.ConfigRuntimeChangeability {
	if changeability == nil || !changeability.IsLive(sectionKey) {
		return gen.ConfigRuntimeChangeabilityRestartRequired
	}

	return gen.ConfigRuntimeChangeabilityLiveApplyAvailable
}

func requireConfigAdmin(ctx context.Context) error {
	principal, ok := auth.PrincipalFromContext(ctx)
	if ok && principal.AccessLevel >= auth.AccessLevelAdmin {
		return nil
	}

	return &gqlerror.Error{
		Message:    "administrative access required",
		Extensions: map[string]any{"code": "FORBIDDEN"},
	}
}

func configMutationError(key string, err error) error {
	switch {
	case errors.Is(err, configapply.ErrSectionNotMutable):
		return gqlerror.Errorf("config section %q is not mutable via API", key)
	case errors.Is(err, configapply.ErrUnknownSection):
		return gqlerror.Errorf("unknown config section %q", key)
	default:
		return gqlerror.Errorf("%s", strings.TrimPrefix(err.Error(), "configapply: "))
	}
}
