package resolvers

import (
	"github.com/bitmagnet-io/bitmagnet/internal/config/configapply"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel/gen"
)

// This file is NOT generated by gqlgen. Helper functions used by resolvers
// live here so they survive `task gen-gql` regeneration. gqlgen relocates any
// non-resolver helper it finds inside *.resolvers.go into a commented-out
// "!!! WARNING !!!" block, which breaks the build because the call site is
// left intact. Keeping helpers in a separate non-generated file avoids that.

// configRuntimeChangeability reports whether a section has a registered
// live-apply path.
func configRuntimeChangeability(
	changeability configapply.Changeability,
	sectionKey string,
) gen.ConfigRuntimeChangeability {
	if changeability == nil || !changeability.IsLive(sectionKey) {
		return gen.ConfigRuntimeChangeabilityRestartRequired
	}

	return gen.ConfigRuntimeChangeabilityLiveApplyAvailable
}
