package resolvers

import (
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel/gen"
)

// This file is NOT generated by gqlgen. Helper functions used by resolvers
// live here so they survive `task gen-gql` regeneration. gqlgen relocates any
// non-resolver helper it finds inside *.resolvers.go into a commented-out
// "!!! WARNING !!!" block, which breaks the build because the call site is
// left intact. Keeping helpers in a separate non-generated file avoids that.

// configRuntimeChangeability reports whether a section can be updated without
// a restart. Today only the LLM sub-config of "classifier" has a live Update()
// path (llm.Registry.Update). Every other section is restart-required.
//
// This is an explicit allowlist rather than a heuristic: the cost of wrongly
// claiming LIVE_APPLY_AVAILABLE is that an operator expects a change to take
// effect immediately and is misled. When a real live-apply path is added for
// another section, add its key here.
func configRuntimeChangeability(sectionKey string) gen.ConfigRuntimeChangeability {
	switch sectionKey {
	case "classifier":
		// llm.Registry.Update() exists and can swap providers at runtime.
		// NOTE: no production caller invokes it today; the label advertises
		// the capability, not that it is currently wired to an API.
		return gen.ConfigRuntimeChangeabilityLiveApplyAvailable
	default:
		return gen.ConfigRuntimeChangeabilityRestartRequired
	}
}
