package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/bitmagnet-io/bitmagnet/internal/gql"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel/gen"
)

// UpdateLlm is the resolver for the updateLlm field.
func (r *dashboardMutationResolver) UpdateLlm(ctx context.Context, obj *gen.DashboardMutation, input gen.DashboardLlmConfigInput) (gen.DashboardLlmState, error) {
	return r.updateDashboardLlm(input)
}

// TestLlmConnection is the resolver for the testLlmConnection field.
func (r *dashboardMutationResolver) TestLlmConnection(ctx context.Context, obj *gen.DashboardMutation) (gen.DashboardLlmConnectionResult, error) {
	return r.testDashboardLlmConnection(ctx)
}

// RunLlmBenchmark is the resolver for the runLlmBenchmark field.
func (r *dashboardMutationResolver) RunLlmBenchmark(ctx context.Context, obj *gen.DashboardMutation, sampleSize int) (gen.DashboardLlmBenchmark, error) {
	return r.runDashboardLlmBenchmark(ctx, sampleSize)
}

// DashboardMutation returns gql.DashboardMutationResolver implementation.
func (r *Resolver) DashboardMutation() gql.DashboardMutationResolver {
	return &dashboardMutationResolver{r}
}

type dashboardMutationResolver struct{ *Resolver }
