package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/bitmagnet-io/bitmagnet/internal/gql"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel/gen"
)

// Events is the resolver for the events field.
func (r *llmQueryResolver) Events(ctx context.Context, obj *gen.LlmQuery, limit *int) ([]gen.LlmClassificationEvent, error) {
	return llmEvents(r.LlmRecorder, limit), nil
}

// Stats is the resolver for the stats field.
func (r *llmQueryResolver) Stats(ctx context.Context, obj *gen.LlmQuery, windowMinutes *int) (gen.LlmStats, error) {
	return llmStats(ctx, r.LlmRecorder, r.QueueMetricsClient, r.ClassifierConfig, windowMinutes)
}

// LlmQuery returns gql.LlmQueryResolver implementation.
func (r *Resolver) LlmQuery() gql.LlmQueryResolver { return &llmQueryResolver{r} }

type llmQueryResolver struct{ *Resolver }
